### ISSUE TITLE
Advanced SQL Puzzles DDL.sql

### ISSUE THREAD

**Issue by MikeSpike666** [smpetersgithub/AdvancedSQLPuzzles#30]
Hi!

Found a few small issues in "In Advanced SQL Puzzles DDL.sql" file. Mostly re. uppercase/lowercase which my server is sensitive to.

* Row 284 - The query referes to "Workflow" instead of "WorkFlow".
* Row 334 - A CRLF between / and * is breaking the comment
* Row 1075 - "StartDAte" instead of "StartDate"
* Row 1126 - "ScheduleID" instead of "ScheduleId"
* Row 1134 - "ScheduleID" instead of "ScheduleId" and "StartTIme" instead of "StartTime"

/Mike

**Comment by smpetersgithub** [comment]
Thank you!!!!   I'm updating this now.   Let me know if you see anything else.  Thank you again!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: MikeSpike666 ***@***.***>
Sent: Tuesday, February 14, 2023 2:25:59 AM
To: smpetersgithub/AdvancedSQLPuzzles ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [smpetersgithub/AdvancedSQLPuzzles] Advanced SQL Puzzles DDL.sql (Issue #30)


Hi!

Found a few small issues in "In Advanced SQL Puzzles DDL.sql" file. Mostly re. uppercase/lowercase which my server is sensitive to.

  *   Row 284 - The query referes to "Workflow" instead of "WorkFlow".
  *   Row 334 - A CRLF between / and * is breaking the comment
  *   Row 1075 - "StartDAte" instead of "StartDate"
  *   Row 1126 - "ScheduleID" instead of "ScheduleId"
  *   Row 1134 - "ScheduleID" instead of "ScheduleId" and "StartTIme" instead of "StartTime"

/Mike
